apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegramgpt-marquezchat-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramgpt-marquezchat
  template:
    metadata:
      labels:
        app: telegramgpt-marquezchat
    spec:
      containers:
        - name: telegramgpt-marquezchat
          image: docker.io/smarquezp/telegramgpt-marquezchat:xxGITHUB_SHAxx
          ports:
            - containerPort: 3000
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: xxTELEGRAM_BOT_TOKENxx
            - name: OPENAI_API_KEY
              value: xxOPENAI_API_KEYxx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
