apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegramgpt-marquezchat-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramgpt-marquezchat
  template:
    metadata:
      labels:
        app: telegramgpt-marquezchat
    spec:
      containers:
        - name: telegramgpt-marquezchat
          image: docker.io/smarquezp/telegramgpt-marquezchat:[[GITHUB_SHA]]
          ports:
            - containerPort: 3000
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: [ [ TELEGRAM_BOT_TOKEN ] ]
            - name: OPENAI_API_KEY
              value: [ [ OPENAI_API_KEY ] ]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
