apiVersion: v1
kind: Service
metadata:
  name: telegramgpt-marquezchat-service
spec:
  selector:
    app: telegramgpt-marquezchat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
