name: Deploy to GCP Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/smarquezp/telegramgpt-marquezchat:${{ github.sha }} .
          docker push docker.io/smarquezp/telegramgpt-marquezchat:${{ github.sha }}
        continue-on-error: false

      - name: Activate service account
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          gcloud auth activate-service-account --key-file=$(pwd)/gcp-key.json
          gcloud container clusters get-credentials ${{ vars.GCP_CLUSTER_NAME }} --zone ${{ vars.GCP_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
        continue-on-error: false

      - name: Install plugin google-cloud-sdk-gke-gcloud-auth-plugin
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl sudo
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update -y && sudo apt-get install -y google-cloud-cli
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
        continue-on-error: false

      - name: Replace variables in deployment.yaml and deploy to GCP Kubernetes
        run: |
          sed -i "s|'\xxGITHUB_SHAxx'|'${{ github.sha }}'|g" k8s/deployment.yaml
          sed -i "s|'\xxTELEGRAM_BOT_TOKENxx'|'${{ secrets.TELEGRAM_BOT_TOKEN }}'|g" k8s/deployment.yaml
          sed -i "s|'\xxOPENAI_API_KEYxx'|'${{ secrets.OPENAI_API_KEY }}'|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -n apps
        continue-on-error: false
