name: Deploy to GCP Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/smarquezp/telegramgpt-marquezchat:${{ github.sha }} .
          docker push docker.io/smarquezp/telegramgpt-marquezchat:${{ github.sha }}
        continue-on-error: false

      - name: Deploy to GCP Kubernetes
        run: |
          gcloud auth activate-service-account --key-file=<(echo "${{ secrets.GCP_SA_KEY }}")
          gcloud container clusters get-credentials ${{ vars.GCP_CLUSTER_NAME }} --zone ${{ vars.GCP_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/telegramgpt-marquezchat-deployment telegramgpt-marquezchat=docker.io/smarquezp/telegramgpt-marquezchat:${{ github.sha }}
        continue-on-error: false
